[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N"]
[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[project]
name = "mywellbeing"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "flet",
    "flet-map",
    "flet-geolocator",
    "pg8000",
    "certifi",
    "python-dotenv",
    "bcrypt",
    "requests",
    "plyer",
    "flet-permission-handler",
    "resend"
]

[tool.flet]
org = "com.yourname.mywellbeing"
product = "MyWellbeing"

[tool.flet.app]
path = "src"
module_name = "main"

[tool.flet.android.permission]
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true
"android.permission.ACCESS_BACKGROUND_LOCATION" = true
[tool.flet.permissions]
location = true

[tool.flet.android]
dependencies = ["flet_geolocator", "flet_permission_handler", "flet_map"]
