#name of Github Action CI
name: CSC2033 CI Test

# used to determine when it wil be run
on:
  #will run when a pull request is done on main branch
  pull_request:
    branches:
      - main
  #will run when push request is done on any branch NOT main
  push:
    branches-ignore:
      - main
# the jobs that will be tested
jobs:
  test:
    #sets up tests on ubuntu on the latest version
    runs-on: ubuntu-latest
    steps:
      #check the repository is valid
      - name: "Checks Repository"
        uses: actions/checkout@v4
      #makes sure python is set up properly
      - name: "Set Up Python"
        uses: actions/setup-python@v5
        with:
          #specifies python version
          python-version: "3.11"
      #install dependencies code needs to run
      - name: "Install Dependencies"
        #uses python to make sure pip is up to date and install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Run Tests with pytest"
        env:
          PYTHONPATH: ${{ github.workspace }}/python
        run: |
          pytest python/tests
          
